<div class="bg-info text-white text-center p-2">
	Busca de todos os produtos		
</div>	

<table class="table table-hover mb-3">	
	<thead>
		<tr>
			<th>Produto</th>
			<th>Descricao</th>
		</tr>
	</thead>

	<tbody>		
		<?php foreach ($this->view->produtos as $produto) { ?>
			<tr>
				<td><?= $produto['nome'] ?></td>
				<td><?= $produto['descricao'] ?></td>
			</tr>
		<?php } ?>		
	</tbody>
</table>